#ifndef AXMLDEC_CONFIG_HPP
#define AXMLDEC_CONFIG_HPP

#ifndef AXMLDEC_VERSION_MAJOR
#define AXMLDEC_VERSION_MAJOR 0
#endif

#ifndef AXMLDEC_VERSION_PATCH
#define AXMLDEC_VERSION_PATCH 0
#endif

#ifndef AXMLDEC_VERSION_MINOR
#define AXMLDEC_VERSION_MINOR 0
#endif

#ifndef AXMLDEC_BUILD_TIMESTAMP
#define AXMLDEC_BUILD_TIMESTAMP ""
#endif

#endif
